### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Ilithy**
Last commits for French translation

### CODE REVIEW

**Comment by Alfavio** [comment]
@Ilithy This files are not required. Or I am wrong?

**Comment by Ilithy** [comment]
These are the files present in the basic values folder, usually I integrate all the files, but they have not been modified, it is up to you to tell me if they are necessary in this folder 😊

**Comment by Alfavio** [comment]
@Ilithy No, this files are not required for translation. Only string.xml is essential,

**Comment by Alfavio** [comment]
Thank you too

**Pull request closed without merging**
